# Generated by Django 3.0.2 on 2020-01-15 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ocr_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OCRInstance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CLOFFER_ID', models.IntegerField()),
                ('REQT_DTTM', models.DateTimeField(auto_now_add=True)),
                ('MSG_CTNT', models.CharField(max_length=4000, null=True)),
                ('REG_DTTM', models.DateTimeField(auto_now_add=True)),
                ('RSTR_USER_NO', models.CharField(max_length=10)),
                ('REG_DEPT_CD', models.CharField(max_length=10)),
            ],
        ),
        migrations.DeleteModel(
            name='Person',
        ),
    ]
