# Generated by Django 3.0.2 on 2020-01-20 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ocr_app', '0002_auto_20200115_1357'),
    ]

    operations = [
        migrations.AddField(
            model_name='ocrinstance',
            name='CHG_DTTM',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
