# Generated by Django 3.0.2 on 2020-01-20 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ocr_app', '0005_remove_ocrinstance_retr_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='ocrinstance',
            name='RETR_URL',
            field=models.URLField(default='test.html', unique=True),
        ),
    ]
