# Generated by Django 3.0.2 on 2020-01-20 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ocr_app', '0006_ocrinstance_retr_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ocrinstance',
            name='CHG_DTTM',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='ocrinstance',
            name='REG_DTTM',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='ocrinstance',
            name='REQT_DTTM',
            field=models.DateTimeField(),
        ),
    ]
