# Generated by Django 3.0.2 on 2020-01-20 06:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ocr_app', '0007_auto_20200120_1332'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ocrinstance',
            name='RETR_URL',
        ),
    ]
